### ISSUE TITLE
cffi.error.VerificationError (undefined symbol: SSLv2_client_method)

### ISSUE THREAD

**Issue by daria-taria** [GoogleCloudPlatform/training-data-analyst#313] opened 2018-10-24 08:04 UTC
Hi, 
Running the first block of feateng.ipynb notebook results in cffi.error.VerificationError so the rest doesn't work as well. The same notebook worked fine yesterday.

**Comment by zeevikal** [comment] 2018-10-24 13:33
I'm getting the same error. I think the issue is incompatible versions of python (2 because of beam usage) and SSL.
I saw the notebook was updated <24 hours ago so maybe it will be fixed soon :)

**Comment by salmariazi** [comment] 2018-10-26 20:48
I'm getting the same error and really need it since I built my whole pipeline based on this example.

**Comment by ekunnii** [comment] 2018-10-27 02:42
For notebook of tftransform.ipynb, please use below commands. 
%%bash
source activate py2env
conda install -y pytz==2018.4
conda update -y pyopenssl
pip uninstall -y google-cloud-dataflow
pip install apache-beam[gcp] tensorflow_transform==0.8.0

I think this issue might be caused by installing pytz in conda. And I am able to complete the whole notebook after above changes.

**Closed** 2019-02-05 17:08 UTC
